### ISSUE TITLE
Version 1.5 Here - Version 1.6 on WordPress

### ISSUE THREAD

**Issue by innesst** [petera703/VPNMyWay#2]
Was wondering why the latest version was not uploaded, and if you could upload the latest executable release in case there is any issue with WordPress in the future.

**Comment by petera703** [comment]
Hi, you're right but 1.6 was just a tweak to the installer, to help a user who wanted to run it in unattended mode back in 2016. When I recently decided to make VPNMyWay open source, the installer tweak wasn't readily available as it's on a VM I'm not regularly using atm. I will look to retrieve it at some point but hopefully anyone needing that feature can just make the same tweak to support the new setup command parameter.
